name: stronger_muscles
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
  
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_core: ^4.2.0
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  hive_flutter: ^1.1.0
  google_sign_in: ^7.2.0
  flutter_svg: ^2.2.1
  icons_launcher: ^3.0.3
  easy_image_viewer: ^1.5.1
  intl: ^0.20.2
  google_maps_flutter: ^2.14.0  
  flutter_lints: ^6.0.0
  http: ^1.2.0
  flutter_dotenv: ^6.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  internet_connection_checker_plus: ^2.9.1+2
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    # analyzer: ^10.0.1
  # flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  freezed: ^2.5.2


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icon/
    - .env
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
icons_launcher:
  image_path: "assets/icon/ChatGPT2.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
flutter_intl:
  enabled: true
